name: Build and test

on:
  workflow_dispatch:
  push:
    branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish     
      run: dotnet publish --no-restore --output "linux64_musl"
    - name: Copy dockerfile 
      run: mv ci/Dockerfile linux64_musl/Dockerfile
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Application_Artifact
        path: ${{github.workspace}}/linux64_musl
        
      # setup Docker buld action
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Build image and push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        # relative path to the place where source code with Dockerfile is located
        context: ${{github.workspace}}/linux64_musl
        # Note: tags has to be all lower-case
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/assistantbot:latest
        push: true

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}