name: Build and test

on:
  workflow_dispatch:
  push:
    branches: [ master, testAction ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish     
      run: dotnet publish -r linux-musl-x64 --no-restore --output "..\linux64_musl" --self-contained true -p:PublishTrimmed=true
    - name: Copy dockerfile 
      run: mv ci/Dockerfile ../linux64_musl/Dockerfile
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Application_Artifact
        path: ../linux64_musl
